version: '3.8'
services:
  db:
    image: mysql:8.0.25
    environment: 
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/sql
volumes:
  db-data: